# -*- coding: utf-8 -*-
"""Web_Scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xrWl6ZFlLTMfr-umF43a8vfyixMDOgId
"""

import requests
import bs4
from bs4 import BeautifulSoup


# Define headers for the request
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299"
}

# Define the URL to scrape
URL = "https://bingewatch.to/movies"

# Conduct a request of the stated URL above with headers included
page = requests.get(URL, headers=headers)

# Specify a desired format of “page” using the html parser - this allows python to read the various components of the page, rather than treating it as one long string.
soup = BeautifulSoup(page.text, "html.parser")

# Print soup in a more structured tree format that makes for easier reading
##print(soup.prettify())


movies_box = soup.find('div', attrs={'class': 'section-items section-items-default'})
movies = movies_box.find_all('div', attrs={'class': 'item'})
for movie in movies:
  #print(movie)
  print(movie.find('h3', attrs={'class': 'movie-name'}).get_text())